name: Delete Merged Branch

on:
  push:
    branches:
      - develop
      
jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Delete merged branch
        run: |
          MERGED_BRANCHES=$(git branch --merged | grep -v "develop")
          if [ ! -z "$MERGED_BRANCHES" ]; then
            echo "$MERGED_BRANCHES" | xargs git branch -d
            echo "$MERGED_BRANCHES" | xargs -n 1 git push origin --delete
          fi
